### ISSUE TITLE
Add maketrails script

### ISSUE THREAD

**Issue by travisbrady** [tansey/gfl#2]
The README mentions a `maketrails` script to be used for preprocessing but the repo contains no such script. Can that be added?

thank you

**Comment by tansey** [comment]
This actually reminded me that I needed to rework the API a bit, so thanks!

I've now changed it so that maketrails is no longer necessary. For anything that's not a huge (1M+ nodes), regular, grid graph, the benefits of having a user generate their own trails is very small.

You can now just call `graphfl data.csv edges.csv --o smoothed.csv` and it will generate trails instantly using a fast, greedy heuristic. If you want to do it from within python, you can call `pygfl.easy.solve_gfl` with just data and edges numpy matrices.

Note that this is not in the latest pip version yet, so you'll have to pull from source to get this.

**Comment by travisbrady** [comment]
Excellent. Thanks very much, @tansey and excellent job overall turning the paper into truly usable software.
